# Generated by Django 5.0.2 on 2025-02-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("modelo", models.CharField(max_length=50)),
                ("fabricante", models.CharField(max_length=50)),
                ("pais_fabricante", models.CharField(max_length=50)),
                ("cantidad_asientos", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("nacionalidad", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vuelos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais_destino", models.CharField(max_length=100)),
                ("ciudad_destino", models.CharField(max_length=100)),
                ("fecha_salida", models.DateTimeField()),
                ("fecha_arribo", models.DateTimeField()),
                (
                    "tipo_vuelo",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        default="NACIONAL",
                        max_length=13,
                    ),
                ),
                (
                    "avion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicacion.avion",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicacion.terminal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Boleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_asiento", models.IntegerField()),
                (
                    "clase_asiento",
                    models.CharField(
                        choices=[
                            ("PRIMERA", "Primera Clase"),
                            ("SEGUNDA", "Segunda Clase"),
                            ("TERCERA", "Tercera Clase"),
                        ],
                        default="TERCERA",
                        max_length=10,
                    ),
                ),
                ("precio_pagado", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "pasajero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicacion.pasajero",
                    ),
                ),
                (
                    "vuelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicacion.vuelos",
                    ),
                ),
            ],
        ),
    ]
