# Generated by Django 5.0.2 on 2025-02-03 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacion", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vuelos",
            new_name="Vuelo",
        ),
    ]
